version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "daily"
