version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*/action.yml"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "daily"
