name: setup-kubernetes
author: "The Flux Authors"
description: Setups Kubernetes Kind cluster and Docker BuildKit for Flux controller e2e testing
inputs:
  go-version:
    description: 'Go version to setup'
    required: true
  kind-version:
    description: 'Kind version to setup'
    required: false
    default: 'v0.30.0'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Setup Kustomize
      uses: fluxcd/pkg/actions/kustomize@bf02f0a2d612cc07e0892166369fa8f63246aabb # main
    - name: Setup QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    - name: Setup Kubernetes
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        version: ${{ inputs.kind-version }}
        cluster_name: kind
