name: controller-release

on:
  workflow_call:
    inputs:
      controller:
        description: 'controller name'
        required: true
        type: string
      release-candidate-prefix:
        description: 'release candidate image tag prefix'
        required: true
        type: string
    secrets:
      github-token:
        description: 'GitHub token (for pushing to GHCR and creating GitHub releases)'
        required: true
      dockerhub-token:
        description: 'Docker Hub token'
        required: true
    outputs:
      release-digests:
        description: 'Release artifacts digests compatible with SLSA'
        value: ${{ jobs.release.outputs.release-digests }}
      image-name:
        description: 'Published container image name (without the registry)'
        value: ${{ jobs.release.outputs.image-name }}
      image-digest:
        description: 'Published container image digest'
        value: ${{ jobs.release.outputs.image-digest }}

jobs:
  release:
    outputs:
      release-digests: ${{ steps.slsa.outputs.release-digests }}
      image-name: ${{ steps.slsa.outputs.image-name }}
      image-digest: ${{ steps.slsa.outputs.image-digest }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating the GitHub release.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for pushing and signing container images.
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@9a8c0edd5da84dc51a585738c67e3a3950d7fbf0 # main
      - name: Prepare
        id: prep
        env:
          GIT_REF: ${{ github.ref }}
          GIT_SHA: ${{ github.sha }}
          RELEASE_CANDIDATE_PREFIX: ${{ inputs.release-candidate-prefix }}
        run: |
          VERSION="${RELEASE_CANDIDATE_PREFIX}-${GIT_SHA::8}"
          if [[ $GIT_REF == refs/tags/* ]]; then
            VERSION=${GIT_REF/refs\/tags\//}
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - name: Setup QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: fluxcdbot # not necessary for ghcr.io
          password: ${{ secrets.github-token }}
      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ github.repository_owner == 'fluxcd' && 'fluxcdbot' || github.repository_owner }}
          password: ${{ secrets.dockerhub-token }}
      - name: Generate images meta
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: |
            ${{ github.repository_owner }}/${{ inputs.controller }}
            ghcr.io/${{ github.repository_owner }}/${{ inputs.controller }}
          tags: |
            type=raw,value=${{ steps.prep.outputs.VERSION }}
      - name: Publish images
        id: build-push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          sbom: true
          provenance: true
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: v2.6.1 # TODO: remove after Flux 2.8 with support for cosign v3
      - name: Sign images
        env:
          COSIGN_EXPERIMENTAL: 1
          CONTROLLER: ${{ inputs.controller }}
          DIGEST: ${{ steps.build-push.outputs.digest }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          cosign sign --yes ${REPOSITORY_OWNER}/${CONTROLLER}@${DIGEST}
          cosign sign --yes ghcr.io/${REPOSITORY_OWNER}/${CONTROLLER}@${DIGEST}
      - name: Generate release artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          CONTROLLER: ${{ inputs.controller }}
        run: |
          mkdir -p config/release
          kustomize build ./config/crd > ./config/release/${CONTROLLER}.crds.yaml
          kustomize build ./config/manager > ./config/release/${CONTROLLER}.deployment.yaml
      - uses: anchore/sbom-action/download-syft@17ae1740179002c89186b61233e0f892c3118b11 # v0.23.0
      - name: Create release and SBOM
        id: run-goreleaser
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
      - name: Generate SLSA metadata
        id: slsa
        env:
          ARTIFACTS: "${{ steps.run-goreleaser.outputs.artifacts }}"
          CONTROLLER: ${{ inputs.controller }}
          VERSION: ${{ steps.prep.outputs.version }}
          BUILD_DIGEST: ${{ steps.build-push.outputs.digest }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          release_digests=$(echo $ARTIFACTS | jq --raw-output '.[] | {name, "digest": (.extra.Digest // .extra.Checksum)} | select(.digest) | {digest} + {name} | join("  ") | sub("^sha256:";"")' | base64 -w0)
          echo "release-digests=$release_digests" >> $GITHUB_OUTPUT

          image_name=${REPOSITORY_OWNER}/${CONTROLLER}:${VERSION}
          echo "image-name=$image_name" >> $GITHUB_OUTPUT

          image_digest=${BUILD_DIGEST}
          echo "image-digest=$image_digest" >> $GITHUB_OUTPUT
