name: lint

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install action lint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Run action lint
        run: |
          find .github/workflows -name '*.yaml' | xargs ./actionlint
