name: lint

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install action lint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Run action lint
        run: |
          find .github/workflows -name '*.yaml' | xargs ./actionlint
